### ISSUE TITLE
Graphics with pixie.js

### ISSUE THREAD

**Issue by MrApplejuice** [xarion/congenial-parakeet#1]
Disregarding everything we talked about earlier today, I suggest to just use pixie.js. It allows us to control aspect of the graphics through a nice game-engine API that is well documented. I tested GDevelop5 as well, but that is very point&clicky - probably something you cannot manage in a collaborative project.

Pixie.js actually clicks with me though. I added a ridiculous test in the corresponding branch - test it if you want. Here some useful links:

- Very nice docs: http://pixijs.download/release/docs/index.html
- Tutorials: http://www.pixijs.com/tutorials
- Examples (actually Feature Demos): https://pixijs.io/examples/#/basics/basic.js
- Demos: https://github.com/pixijs/pixi.js#demos

I will amke the stuff more useful tomorrow!

**Comment by xarion** [comment]
i assume that this is done, pixi is good!
